CREATE DOMAIN IF NOT EXISTS "TEXT" AS CLOB;
CREATE DOMAIN IF NOT EXISTS "LONGTEXT" AS CLOB;
CREATE DOMAIN IF NOT EXISTS TEXT AS CLOB;
CREATE DOMAIN IF NOT EXISTS LONGTEXT AS CLOB;

CREATE TABLE IF NOT EXISTS persistent_logins (
    username  VARCHAR(64) NOT NULL,
    series    VARCHAR(64) PRIMARY KEY,
    token     VARCHAR(64) NOT NULL,
    last_used TIMESTAMP NOT NULL
);
